src/audio/AudioPlayer.ts
Resolves #2.
You can now configure the AudioPlayer's behaviours with an optional parameter:
```js
createAudioPlayer({
behaviours: {
noSubscriber: NoSubscriberBehaviour.Pause // default
}
});
```
=> feat!: ability to set AudioPlayer behaviours

package-lock.json, package.json, src/DataStore.ts, src/VoiceConnection.ts
Resolves #15.
It is cleaner to listen to the specific `VOICE_SERVER_UPDATE` and `VOICE_STATE_UPDATE` packets from the Discord.js WebSocketManager as opposed to listening to the `raw` event from the main client and filtering the packets.
=> refactor(DataStore): hook into WebSocketManager

src/audio/AudioPlayer.ts
=> feat(AudioPlayer): throw when playing ended audio

src/audio/index.ts, src/index.ts, src/joinVoiceChannel.ts, src/util/index.ts
Resolves #23 - exports all the public types (classes, interfaces, functions, enums) in the entry point of the library
=> feat: export all public types

src/audio/AudioPlayer.ts
=> feat(AudioPlayer): propagate stream errors

src/audio/AudioResource.ts
=> feat(AudioResource): make createAudioResource options optional

src/audio/AudioPlayer.ts
=> feat(AudioPlayer): make createAudioPlayer options optional

package.json
=> chore(pack): declare 'files' param within package.json

examples/basic/README.md, examples/basic/basic-example.ts, src/util/entersState.ts, src/util/index.ts
Resolves #41.
- Exports the `entersState` utility function
- Updates the example to use the exported function
=> feat: entersState helper function

src/audio/AudioPlayer.ts, src/audio/TransformerGraph.ts, src/audio/index.ts, src/networking/Networking.ts
=> chore: American English consistency

package.json, src/DataStore.ts, src/VoiceConnection.ts, src/audio/AudioPlayer.ts, src/audio/AudioResource.ts, src/audio/TransformerGraph.ts, src/joinVoiceChannel.ts, src/networking/Networking.ts, src/networking/VoiceUDPSocket.ts, src/networking/VoiceWebSocket.ts, src/util/entersState.ts, src/util/generateDependencyReport.ts, tsconfig.json
The `@remarks` blocks can be modified or should be changed actually. They are usually used to indicate further explaination and not just a brief summary, but this is for another PR.
This should be merged before #56 (if that gets merged at all, it probably shouldn't but the changes in it should definitely be applied in another PR without docs deployment to GH-Pages)
=> docs: cleanup docs with correct syntax

README.md
=> chore(README): add badges

jest.config.js, src/DataStore.ts, src/audio/__tests__/AudioPlayer.test.ts
Adds tests for the AudioPlayer's core functionality.
=> test(AudioPlayer): add tests for core functionality

src/networking/VoiceUDPSocket.ts, src/networking/__tests__/VoiceUDPSocket.test.ts
Adds unit tests to VoiceUDPSocket, and also fixes an issue raised in testing. Previously, if an unexpected message was received on the socket during IP discovery, then an unhandled error would be thrown. This has been fixed, the caller of the parsing function now handles errors by discarding bad packets. The parsing function also validates the IP address.
=> test(VoiceUDPSocket): unit tests

README.md
currently the readme links to master while the branch is actually main
=> docs(README): fix branch in contributing link

README.md
- For consistency with https://github.com/discordjs/discord.js/pull/5739
=> chore(README): use new blurple for discord.js server badge

examples/README.md, examples/radio-bot/.gitignore, examples/radio-bot/README.md, examples/radio-bot/config.example.json, examples/radio-bot/index.js, examples/radio-bot/package.json
Resolves #115.
Adds an updated version of [discord-radio-bot](https://github.com/amishshah/discord-radio-bot) as a JavaScript example. Also adds a TOC to the examples directory.
=> docs(Examples): add a JavaScript example

package-lock.json, package.json
Heck did I know I had to call `bundle.write()` after creating the rollup bundle
I guess I should've read rollup docs more carefully, lol.
<details>
<summary>Click here to view the <code>dist/index.d.ts</code> after <code>npm publish --dry-run</code>!</summary>
```ts
/// <reference types="node" />
import { Readable, ReadableOptions } from 'stream';
import { VolumeTransformer, opus } from 'prism-media';
import { TypedEmitter } from 'tiny-typed-emitter';
import { GatewayVoiceServerUpdateDispatchData, GatewayVoiceStateUpdateDispatchData } from 'discord-api-types/v8';
import WebSocket, { MessageEvent } from 'ws';
declare type Awaited<T> = T | Promise<T>;
/**
* The different types of stream that can exist within the …
```
=> fix: fixed type bundling for real

examples/basic/adapter.ts, examples/music-bot/src/bot.ts
This changes the `guildID` property in the examples into `guildId`, since it was changed
=> fix(Examples): change `guildID` to `guildId`

examples/basic/basic-example.ts, examples/music-bot/package.json, examples/music-bot/src/bot.ts, examples/music-bot/src/music/subscription.ts, examples/radio-bot/index.js
setTimeout and error Type errors as well as some examples update (interaction and message event)
As we can see in [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve#syntax) resolve needs a value argument when resolving a promise.
Status : Now it is fixed
=> refactor(Examples): update events and fix compilation errors on newer versions of TypeScript

.github/CONTRIBUTING.md
This PR updates the conventional commit format URL
=> chore: update conventional commit URL

src/__tests__/DataStore.test.ts
Add the rest of the tests for DataStore 😄 
=> test(DataStore): add missing tests

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/SUPPORT.md, README.md
- Flexes vanity URL
- Corrects a link so it redirects to this repository's discussions
- A random extra point so it seems like I'm doing stuff
=> chore: Update invite & discussion links
