- package-lock.json
- package.json
- src/VoiceConnection.ts
- src/audio/AudioPlayer.ts
- src/index.ts
- src/networking/Networking.ts
- src/networking/VoiceWebSocket.ts
- src/util/generateDependencyReport.ts
Resolves #1.
- Emitted as a propagated debug message from VoiceWebSocket, through Networking, to VoiceConnection
- State transitions are emitted as debug messages, showing the state before and after the change
- Implemented as `generateDependencyReport`, example output shown below
```
--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.0.1
- discord.js: 12.5.1
- prism-media: 1.2.5
Opus Libraries
- @discordjs/opus: 0.4.0
- opusscript: 0.0.7
Encryption Libraries
- sodium: 3.0.2
- libsodium-wrappers: not found
- tweetnacl: 1.0.3
FFmpeg
- version: 4.2.4-1ubuntu0.1
- libopus: yes
--------------------------------------------------
```
---
Debugging is **opt-in** and can be enabled like so:
```js
joinVoiceChannel(channel, { debug: true });
```
> feat: debugging utilities

- README.md
- package-lock.json
- package.json
Resolves #17.
The audio-related dependencies are removed from `peerDependencies` in package.json, and instead a notice is included in the README instructing the user which dependencies they should install.
> deps: remove peer dependencies

- examples/basic.ts
- src/VoiceConnection.ts
- src/audio/AudioPlayer.ts
- src/audio/PlayerSubscription.ts
Resolves #4 
- Done via the PlayerSubscription interface
- Done implicitly in the state transition to Destroyed
- Done implictly in the state transition
- Adds `subscribe` and `unsubscribe` events to audio player
> feat!: ability to unsubscribe connections from audio players

- package-lock.json
- package.json
This PR moves `@types/*` and `discord-api-types` into `devDependencies` from `dependencies`.  
- I know how to update typings and have done so, or typings don't need updating
> chore(deps): move @types/* and dapi-types to dev deps

- src/VoiceConnection.ts
Line 126 was a duplicate of line 125 when line 126 should have had `oldState` replaced with `newState`
Are we versioning already?
> fix(VoiceConnection): correctly compare subscriptions in state transition

- src/audio/AudioPlayer.ts
Resolves #7.
Previously, you had to wait until a stream was readable, or else it wouldn't have played. This PR introduces a new state, `Buffering`, to audio player. If a stream is not readable when it passed to `AudioPlayer#play()`, then the player transitions into the Buffering state.
In the Buffering state, once the stream becomes readable, the player will transition to the Playing state as normal. If the stream emits the `close` event before it becomes readable, then the player will transitino back to the Idle state.
> feat(AudioPlayer): allow playing streams that are not yet readable

- src/VoiceConnection.ts
- Fixes a bug where attempting to unsubscribe a PlayerSubscription would enter a stack overflow error. The `unsubscribe()` method would call `VoiceConnection#onSubscriptionRemoved()`. This would attempt to call `unsubscribe()` to remove the subscription, however this would again call `onSubscriptionRemoved()`. This would repeat until the overflow error occurs. Fixing this required updating the state before calling `.unsubscribe()` on the subscription, to prevent further calls being made.
- Fixes a bug where you couldn't update the voice state (channel, self mute, self deafen) on an existing voice connection without destroying it first. Now, existing voice connections revert to the Signalling state and a voice state …
> fix(VoiceConnection): unsubscribing + moving channels

- .github/PULL_REQUEST_TEMPLATE.md
The typings line is an oversight we missed during the review of the PR templates, this project does not have typings (instead, it generates them), so it's never applicable.
> chore(GitHub): remove typings line from PR template

- src/audio/AudioResource.ts
- src/audio/TransformerGraph.ts
This PR refactors the transformer graph to a format that is more suitable for constraint satisfaction. One use case has already been implemented, which is volume transforming. Now you can specify that the outputted pipeline should include a volume transformer, and the graph functions will find the lowest cost pipeline that will achieve this.
This will make it possible to address #21. Without this change, it would have been possible for a stream that requires inline volume to have been transcoded to .ogg by FFmpeg (had the change been implemented). However, the extra cost of demuxing, decoding, transforming, then encoding the stream would have outweighed the cost of just transforming the stream to PCM. This PR …
> refactor(TransformerGraph): extra constraint satisfaction

- src/audio/AudioPlayer.ts
- src/audio/AudioResource.ts
Resolves #48 
This PR implements locking for audio resources to prevent audio resources from being played on more than one player simultaneously.
Attempting to play an audio resource that is locked by another player will result in an error being thrown in the `AudioPlayer#play(resource)` method. This method is also idempotent - attempting to play the same resource on the same player repeatedly will result in nothing happening.
> refactor(AudioResource): implement locking

- src/audio/TransformerGraph.ts
Resolves #21.
If the user's FFmpeg installation was compiled with `--enable-libopus`, then we are able to enable an optimisation for certain use cases. This optimisation will use FFmpeg to give an OggOpus output rather than a raw audio output that needs to be encoded to Opus. This allows for:
- No requirement of an Opus library
- Around 10% faster to process the entire audio stream
This requires less work to be done by the library, which is a nice bonus for performance too!
**This optimisation is only taken for arbitrary streams with inline volume disabled**. If you would like to use inline volume, you'll still need an Opus library.
- Code changes have been tested against …
> feat(TransformerGraph): add FFmpeg opus optimization

- src/VoiceConnection.ts
Two bugs were introduced in recent changes:
1. Subscriptions were silently removed whenever the voice connection disconnected. That means when they recovered, they would no longer be subscribed to an audio player.
2. An incorrect assumption was made about what happens when signalling to join a voice channel that the client is already connected to. It is not always the case that a voice server switch is required. Therefore, a Voice Connection will no longer transition to the `Signalling` state when `joinVoiceChannel` is called repeatedly. The packet will still be sent, but a reconnect will only occur if a `VOICE_SERVER_UPDATE` packet is received.
- Code changes have been …
> fix(VoiceConnection): improve recoverability

- src/audio/AudioPlayer.ts
Resolves #57.
Allows users to specify `maxMissedFrames` when creating an audio player:
```ts
createAudioPlayer({
behaviours: {
maxMissedFrames: 5 // default
}
});
```
Each frame is equivalent to 20ms of audio - the default value is therefore 100ms.
You could set this to `Infinity` to disable playback when there are gaps in streams. Useful when you know you will be playing a stream with many gaps in it (e.g. streams that omit silence)
> feat(AudioPlayer): add maxMissedFrames behaviour

- src/DataStore.ts
- src/audio/AudioPlayer.ts
Resolves #53.
Audio players are no longer responsible for their own timing cycles. Instead, they now subscribe to a global timer in the `DataStore`.
When players enter the `Playing` state, they attach themselves to this timer. When they enter the `Idle` state, they detach themselves.
While there are no players attached, the timer is unset and therefore doesn't block the process from exiting.
The timer runs roughly every 20ms while active. At the start of each interval, it has all the active voice connections under the audio players dispatch any buffered audio packets. After this is done, each audio player takes turns in preparing their next audio frame for each of their own voice connections (this is the CPU …
> refactor: use global timer for audio players

- examples/basic/README.md
- examples/basic/adapter.ts
- examples/basic/basic-example.ts
- package-lock.json
- package.json
- src/DataStore.ts
- src/VoiceConnection.ts
- src/joinVoiceChannel.ts
- src/util/adapter.ts
- src/util/generateDependencyReport.ts
- src/util/index.ts
Resolves #64 by implementing an adapter pattern. This removes `@discordjs/voice`'s dependency on Discord.js - it can now be used _anywhere_ (that supports JavaScript). All you need is a connection to the Discord gateway and some "glue" (discussed below).
For example, this enables running `@discordjs/voice`:
- With alternative Node.js Discord API libraries (e.g. [Cordis](https://github.com/cordis-lib) or [Eris](https://github.com/abalabahaha/eris))
- In a distributed architecture (making it scalable!)
When joining a voice channel, you must also specify an `adapter`:
```ts
await joinVoiceChannel({
channelId,
guildId,
adapter
});
```
`adapter` is a function that allows the library and adapter implementer to share …
> feat!: implement adapters

- src/audio/AudioPlayer.ts
- src/audio/AudioResource.ts
This PR defaults the metadata type (T) to unknown as suggested by https://github.com/discordjs/voice/pull/69#pullrequestreview-600160882 (#69)
> refactor(AudioResource): default T to unknown

- src/audio/AudioPlayer.ts
- src/audio/AudioPlayerError.ts
- src/audio/AudioResource.ts
Resolves #68
Example usage:
```ts
interface TrackMetadata {
title: string;
artist: string;
}
const resource = createAudioResource<TrackMetadata>('/my/path/file.mp3', {
metadata: {
title: 'make discord.js voice great again speech',
artist: 'hydrabolt'
}
});
```
> feat(AudioResource)!: use metadata instead of name

- src/audio/AudioPlayer.ts
- src/audio/AudioResource.ts
- src/audio/__tests__/AudioPlayer.test.ts
Resolves #71
Adds `playbackDuration` to both `AudioPlayer` and `AudioResource`:
- `AudioResource.playbackDuration` is incremented by 20ms every time an Opus packet is read from its underlying Opus stream. This value can be thought of as the progress through an audio track. It starts off at 0.
- `AudioPlayer.state.playbackDuration` is available in the `Playing`, `Paused`, and `AutoPaused` states. It is incremented by 20ms every time an Opus packet (whether from the audio resource, or a filler silence packet) is prepared for dispatch by the subscribers. This value can be thought of as the "real" playback time of the bot, including any transmission gaps. It resets back to 0 when playing a new resource.
You can …
> feat: stream time statistics

- src/VoiceConnection.ts
- src/audio/AudioPlayer.ts
- src/audio/index.ts
- src/index.ts
- src/networking/Networking.ts
Improves documentation for the various states of `AudioPlayer`, `VoiceConnection`, and `Networking`.
An refactor was made to `AudioPlayer`, where a state of a playable type is passed to the `_preparePacket` method. This allows it to increment the `playbackDuration` itself without having to perform a status assertion.
- This PR changes the library's interface (additional interfaces exported)
> refactor: split states into a union of interfaces

- src/VoiceConnection.ts
- src/__tests__/VoiceConnection.test.ts
Implements unit tests for the most important functionality within VoiceConnection. Also includes a minor fix (automatic reconnects done by the library never incremented `reconnectAttempts`, only manual reconnects by the user did)
> test(VoiceConnection): add unit tests

- examples/basic/adapter.ts
- src/VoiceConnection.ts
- src/__tests__/VoiceConnection.test.ts
- src/util/adapter.ts
Resolves #78.
When the provider of an adapter realises that the adapter it has provided is no longer valid (e.g. the shard of the guild it is for has disconnected), it can now call a `destroy()` method so that its VoiceConnection can self-destruct.
The example for a Discord.js adapter has been updated to reflect this.
Additionally, the existing `destroy()` function is now required (as opposed to optional), as not handling destroy calls is just bad behaviour.
- This PR includes breaking changes (methods removed or …
> feat: allow adapter creator to call a destroy method

- package-lock.json
- package.json
- src/VoiceConnection.ts
- src/__mocks__/ws.js
- src/networking/Networking.ts
- src/networking/VoiceWebSocket.ts
- src/networking/__tests__/VoiceWebSocket.test.ts
Resolves #70.
Fixes a bug in VoiceWebSocket where if no heartbeat acknowledge was ever received, then the WebSocket would continually keep heartbeating instead of disconnecting.
Adds tests to VoiceWebSocket and the new feature.
> feat: add ping stats

- src/audio/AudioResource.ts
- src/audio/__tests__/AudioResource.test.ts
Resolves #83. Simplifies playing streams with specific types, keeping any optimisations in the transcoder pipeline:
```ts
// old
createAudioResource(raw.pipe(new prism.opus.Encoder(options)), { inputType: StreamType.Opus });
createAudioResource(opus.pipe(new prism.opus.Decoder(options)), { inputType: StreamType.Raw });
createAudioResource(ogg.pipe(new prism.opus.OggDemuxer()), { inputType: StreamType.Opus });
// new
createAudioResource(raw.pipe(new prism.opus.Encoder(options)));
createAudioResource(opus.pipe(new prism.opus.Decoder(options)));
createAudioResource(ogg.pipe(new prism.opus.OggDemuxer()));
```
Additionally, if you specify `inlineVolume` as true and pass in a prism-media VolumeTransformer, the pipeline …
> feat: createAudioResource now infers stream type

- src/VoiceConnection.ts
- src/networking/Networking.ts
- src/networking/VoiceUDPSocket.ts
- src/networking/__tests__/VoiceUDPSocket.test.ts
Adds a keep alive mechanism to the UDP socket, that allows 60 seconds for Discord to echo keep alive messages back to the sender. If 60 seconds pass, the UDP socket emits an error warning that a connection between the client and Discord is likely unavailable, causing the voice connection to attempt to reconnect.
A breaking change because `connection.ping` is now of type ` { ws: ?number, udp: ?number }` instead of just `?number`.
- This PR includes breaking changes (methods removed or renamed, parameters moved or …
> feat: keep alive mechanism to detect connectivity to Discord

- src/networking/Networking.ts
- src/networking/VoiceUDPSocket.ts
- src/networking/VoiceWebSocket.ts
- src/networking/__tests__/VoiceWebSocket.test.ts
Refactors the library to use typed event emitters internally. Also fixes an inaccuracy within a test, as well as fixing an error emission bug in `VoiceWebSocket`.
> feat: use typed event emitters internally

- src/audio/AudioPlayer.ts
- src/audio/AudioResource.ts
- src/audio/__tests__/AudioPlayer.test.ts
Resolves #97.
If an AudioResource does not immediately have data to read when it is added to an AudioPlayer, then the player will enter a Buffering state and wait until the resource _does_ have data to read, at which point it will enter the Playing state.
Existing tests were updated to wait for a resource to have data until playing them, and a new test has been added to test this behaviour.
Please move lines that apply to you out of the comment:
> fix(AudioPlayer): enter Buffering state for resources that are not yet readable

- package-lock.json
- package.json
- src/DataStore.ts
- src/VoiceConnection.ts
- src/__tests__/VoiceConnection.test.ts
- src/networking/Networking.ts
- src/networking/VoiceWebSocket.ts
- src/networking/__tests__/VoiceWebSocket.test.ts
- src/receive/VoiceReceiver.ts
- src/receive/__tests__/VoiceReceiver.test.ts
- src/util/adapter.ts
Resolves #99.
Since a voice connection can now be in a disconnected state _without_ a close code, the close code has now been made optional.
> fix(VoiceConnection): handle nullable endpoint in voice server update payload

- .eslintignore
- examples/music-bot/.eslintrc.json
- examples/music-bot/.gitignore
- examples/music-bot/README.md
- examples/music-bot/auth.example.json
- examples/music-bot/package.json
- examples/music-bot/src/bot.ts
- examples/music-bot/src/music/adapter.ts
- examples/music-bot/src/music/subscription.ts
- examples/music-bot/src/music/track.ts
- examples/music-bot/tsconfig.eslint.json
- examples/music-bot/tsconfig.json
This PR adds an example implementation of a music bot using discord.js. It focuses on:
- Reconnection logic
- Error handling and important state transitions
- Implementing a music queue
- Interesting uses of metadata in AudioResources
> docs: music bot example

- examples/music-bot/src/bot.ts
- examples/music-bot/src/music/subscription.ts
- src/audio/AudioResource.ts
- src/audio/__tests__/AudioPlayer.test.ts
- src/audio/__tests__/AudioResource.test.ts
This adds the optional `encoder` property to an AudioResource, so you could do this for example:
```ts
resource.encoder?.setBitrate(48000);
```
Also simplifies the constructor of AudioResource, as well as fixes the metadata typings. Previously, this was an issue:
```ts
(resource as AudioResource<MyMetadata>).metadata // type of MyMetadata|undefined
```
Even though the AudioResource is given a type, metadata was incorrectly optional. This is now fixed.
> feat(AudioResource): add encoder property, fix type for metadata

- examples/UNLICENSE
- package.json
This PR sub-licenses the examples folder so they're under UNLICENSE, which makes
them public-domain, and as such, it will allow users to legally be able to use
the \[boilerplate] code without needing to attribute the library's MIT license. 
> chore(Legal): added UNLICENSE in examples

- src/audio/AudioResource.ts
`createAudioResource` currently has an invalid return type, this PR fixes it.
> fix(AudioResource): improve accuracy of function signatures

- examples/music-bot/README.md
- examples/music-bot/package.json
- examples/music-bot/src/music/track.ts
- examples/music-bot/tsconfig.json
- package-lock.json
- package.json
- src/util/__tests__/demuxProbe.test.ts
- src/util/demuxProbe.ts
- src/util/index.ts
- src/util/opusDemuxProbe.ts
This adds an Opus audio probing utility that will help with deciding the best way to handle an audio stream. It can determine whether the input stream is a valid WebM or Ogg Opus stream for playing in Discord voice channels (i.e. an Opus stream at 48kHz sample rate and 2 audio channels). This allows you to demux the stream, rather than blindly passing it to FFmpeg, for improved performance. For example:
```ts
import { createReadStream } from 'fs';
import { StreamType, demuxProbe, createAudioResource } from '@discordjs/voice';
async function start() {
// Example verifications
assert.equal(await demuxProbe(createReadStream('file.mp3')), StreamType.Arbitrary);
assert.equal(await …
```
> feat(Util): add Opus audio probing utility

- src/audio/AudioPlayer.ts
- src/audio/AudioResource.ts
- src/audio/__tests__/AudioPlayer.test.ts
- src/audio/__tests__/AudioResource.test.ts
Resolves #119.
By default, resources will now output 5 silence frames after their underlying stream has finished. This means that playing two resources one after the other will give a 100ms delay between both, but will prevent interpolation glitches.
This can be configured:
```ts
createAudioResource(stream, { silencePaddingFrames: 0 }); // disable this feature
createAudioResource(stream, { silencePaddingFrames: 5 }); // default
createAudioResource(stream, { silencePaddingFrames: 10 }); // 200ms worth of silence after resource finishes
```
This is mostly transparent to the AudioPlayer, except for the `#stop()` method. This method will now, by default, cause the player's resource to start outputting its final silence …
> feat!: add silence padding frames to AudioResources

- examples/music-bot/src/music/subscription.ts
- src/VoiceConnection.ts
- src/audio/AudioPlayer.ts
- src/index.ts
- src/networking/Networking.ts
- src/networking/VoiceUDPSocket.ts
- src/networking/VoiceWebSocket.ts
- src/receive/SSRCMap.ts
- src/util/util.ts
- Separates two distinct VoiceConnection disconnected states so they no longer overlap.
- EventEmitters now take event handlers of type `Awaited<void>` (borrowed from @kyranet's implementation in discord.js)
- Music bot example's reconnection logic has been fixed. For some reason I ignored the advice I gave in [the voice guide](https://deploy-preview-595--discordjs-guide.netlify.app/voice/voice-connections.html#handling-disconnects) 😅
> feat: allow awaitable void event listeners, fix VoiceConnection disconnected states

- examples/music-bot/src/music/subscription.ts
- src/VoiceConnection.ts
- src/__tests__/VoiceConnection.test.ts
- Adds `VoiceConnection#disconnect` if you want to keep the VoiceConnection instance while still disconnecting from voice.
- Rename `VoiceConnection#reconnect` to `VoiceConnection#rejoin` for accuracy (it actually attempts to rejoin the voice channel, not just the voice server)
- Rename `VoiceConnection#reconnectAttempts` to `VoiceConnection#rejoinAttempts`
- Allow `VoiceConnection#rejoin` to take a partial JoinConfig. For example, `vc.rejoin({ channelId: 'newid' })`
- This PR includes breaking changes (methods removed …
> feat!(VoiceConnection): add disconnect and rename reconnect to rejoin

- src/util/Secretbox.ts
- src/util/__tests__/Secretbox.test.ts
Resolves #128.
If no valid encryption package is installed, the following error is now thrown (rather than the obscure error shown in #128):
```
throw new Error(`Cannot play audio as no valid encryption package is installed.
^
Error: Cannot play audio as no valid encryption package is installed.
- Install sodium, libsodium-wrappers, or tweetnacl.
- Use the generateDependencyReport() function for more information.
```
> feat(Secretbox): throw fallback error when no encryption package installed

- src/util/Secretbox.ts
This PR types the `methods` object from Secretbox and removes an `any` cast,
with the objective of improving the overall type safety in the library's
internals.
> refactor(Secretbox): type `methods` object

- src/VoiceConnection.ts
- src/audio/AudioPlayer.ts
- This makes `VoiceConnection` emits status events with the their new state type
- Code with new typings
```ts
<VoiceConnection>.on(VoiceConnectionStatus.Ready, (_, newState: VoiceConnectionReadyState) => {
// code
})
```
in favor of
```ts
<VoiceConnection>.on(VoiceConnectionStatus.Ready, (_, newState: VoiceConnectionState) => {
if (newState.status === VoiceConnectionStatus.Ready) {
// code
}
// or
const readyState = newState as VoiceConnectionReadyState;
// code
})
```
> fix(Events): strengthen new state type for status events

- src/VoiceConnection.ts
- src/__tests__/VoiceConnection.test.ts
When using `<VoiceConnection>.rejoin()` with the same channel on ready state, the networking state is not changed. This makes the connection state stuck on the signalling status.
> fix(VoiceConnection): stuck on signalling state when rejoining the same channel on ready state

- src/VoiceConnection.ts
- src/__tests__/VoiceConnection.test.ts
Resolves #138.
Calling `VoiceConnection#disconnect()` didn't actually send the correct voice state update packet to Discord. This has been fixed to null the channelId before sending the packet, and a test exposing this has been added.
> fix(VoiceConnection): disconnect method now actually disconnects

- examples/music-bot/package.json
- src/DataStore.ts
- src/VoiceConnection.ts
- src/__tests__/DataStore.test.ts
- src/__tests__/VoiceConnection.test.ts
- src/__tests__/joinVoiceChannel.test.ts
- src/index.ts
- src/joinVoiceChannel.ts
Resolves #144.
VoiceConnections are now stored in a 2D map (`{group_id -> {guild_id -> voice_connection}}`).
The default global group ID is `default` - this is so the update is backwards compatible. Users may optionally specify their own group ID, e.g. the client ID, when creating their voice connections if they wish to run more than one bot in the process.
Also exposes two new methods:
- `DataStore#getGroups()` - get the full 2D group map
- `DataStore#getVoiceConnections(group = 'default')` - gets the map of guild IDs to voice connections for the given group
- This PR changes the …
> feat: voice channel groups

- examples/basic/adapter.ts
- examples/music-bot/package.json
- package-lock.json
- package.json
- src/DataStore.ts
- src/VoiceConnection.ts
- src/networking/Networking.ts
- src/networking/VoiceWebSocket.ts
- src/networking/__tests__/VoiceWebSocket.test.ts
- src/receive/VoiceReceiver.ts
- src/receive/__tests__/VoiceReceiver.test.ts
- src/util/adapter.ts
Update `discord-api-types` and fix typing problem with `adapterCreator` option
`Type 'InternalDiscordGatewayAdapterCreator' is not assignable to type 'DiscordGatewayAdapterCreator'.`
> chore(Deps): update `discord-api-types` to `0.19.0`

- src/VoiceConnection.ts
- src/__tests__/VoiceConnection.test.ts
- src/networking/Networking.ts
This changes all mentions of `xID` in ConnectionOptions to `xId` for consistency with everything else
> refactor(ConnectionOptions): change `xID` to `xId`

- examples/basic/adapter.ts
Adjusts the discord.js v12 adapter to match the same destroy conditions given by the adapter provided with discord.js v13.
Resolves #153 
> fix(Examples): destroy discord.js v12 adapter less readily

- src/audio/AudioResource.ts
This pr replaces the `once(this.playStream, 'readable')` listener inside audioResouce with a proper `this.playStream.once(...)` listener.
Personally i experienced alot of `audioPlayer failed to enter state playing in ????ms` errors prior to this fix.
The timeout duration had no effect on this.
I calculated that there was a 6 ms latency when using `once(...)` compared to `this.playStream.once(...)`. During this 6 ms the `audioPlayer.play()` function executed missing the if statement for `resouce.playing` and attaching the event listeners **after** `audioResouce readable` event emitted.
> refactor(AudioPlayer): use this.once instead of events.once

- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- package-lock.json
- package.json
- src/util/__tests__/abortAfter.test.ts
- src/util/__tests__/entersState.test.ts
- src/util/abortAfter.ts
- src/util/entersState.ts
- tsconfig.json
Resolves #169 
Allows users to pass in an AbortSignal to `entersState` if they'd like more control than just a timeout over cancelling the operation. Still allows for passing a delay as a number, but the minimum Node.js version has been upped to v16.
```ts
// Still backwards-compatible
await entersState(vc, VoiceConnectionStatus.Ready, 1000);
// New support for AbortSignals
// entersState will abort once 'someEvent' is emitted
const ac = new AbortController();
eventEmitter.once('someEvent', () => ac.abort());
await entersState(vc, VoiceConnectionStatus.Ready, ac.signal);
```
- This PR …
> feat(Util): support AbortSignal in entersState

- examples/basic/adapter.ts
The imported binding `WebSocketShard` is actually never used throughout the code in the `examples/basic/adapter.ts` file, so there's no point in it being there.
> refactor(Examples): remove unused imported binding

- package-lock.json
- package.json
- tsup.config.ts
> fix(esm): resolve esm imports
